version: '3.9'
services:
  db:
    image: mysql:8.0.21
    container_name: db_prisma
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
